config/routes.rb
Rails.application.routes.draw do

  # Root
  root 'pages#home'

  # Devise
  devise_for :users, path: '',
    path_names: {
      sign_in: 'login',
      sign_out: 'logout',
      sign_up: 'register' }

  # Projects 
  resources :projects do
    collection { post :send_bulk }
    resources :contacts do
      resources :messages
    end
    resources :campaigns
  end

  # Incoming Messages
  post 'incoming_message_webhook' => 'twilio#incoming_message'
 
end

app/models/project.rb
class Project < ActiveRecord::Base

  # Associations
  belongs_to :user
  has_many :contacts, dependent: :destroy
  has_many :campaigns, dependent: :destroy
  has_many :messages, dependent: :destroy

  # Validations
  validates :name, presence: true

  # Friendly Id #
  # ------------------------------------------------ #
  extend FriendlyId
  friendly_id :random_slug, use: [:slugged, :finders]

  def random_slug
    self.slug = SecureRandom.hex(5)
  end

  # Send Bulk #
  # ------------------------------------------------ #
  def send_bulk(body, project_id)
    # @client = Twilio::REST::Client.new Settings.twilio.account_sid, Settings.twilio.auth_token
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def index
    @projects = Project.all
    @user_projects = current_user.projects.all
    @user_contacts = current_user.contacts.all
  end

  def show
    @project = Project.find(params[:id])
  end

  def new
    @project = current_user.projects.build
  end

  def edit
  end

  def create
    @project = current_user.projects.build(project_params)
    if @project.save
      redirect_to @project, notice: 'Project was successfully created.'
    else
      render :new
    end
  end

  def update
    if @project.update(project_params)
      redirect_to @project, notice: 'Project was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_path, notice: 'Project was successfully destroyed.'
  end

  # def bulk_delivery
  #   @project.send_bulk(params[:body], params[:project_id])
  # end

  private
    def set_project
      @project = Project.find(params[:id])
    end

    def project_params
      params.require(:project).permit(:name)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<div class="bg-light lter b-b wrapper-md ng-scope">
  <h1 class="m-n font-thin h3">
    Projects Overview
    <span class="badge"><%= current_user.projects.count %></span>
  </h1>
  <small class="text-muted">Bootstrap components written in pure AngularJS</small>
</div>

<div class="wrapper-md">



  <div class="row">
    <div class="col-md-8">

      <!-- Project List -->
      <div class="panel no-border">
        <div class="panel-heading wrapper b-b b-light" style="padding:15px;">
          <span class="text-xs text-muted pull-right">
            <i class="fa fa-circle text-primary m-r-xs"></i> 12
            <i class="fa fa-circle text-info m-r-xs m-l-sm"></i> 30
            <i class="fa fa-circle text-warning m-r-xs m-l-sm"></i> 98
          </span>
          <h4 class="font-thin m-t-none m-b-none text-muted">Projects</h4>              
        </div>
        <ul class="list-group list-group-lg m-b-none">

          <% @user_projects.each do |project| %>
            <li class="list-group-item">

              <a href="" class="thumb-sm m-r">
                <img src="img/a1.jpg" class="r r-2x">
              </a>
              <span class="pull-right label bg-primary inline m-t-sm">Admin</span>
              <%= link_to project.name, project %>

            </li>
          <% end %>

        </ul>
        <div class="panel-footer">
          <%= link_to new_project_path, class: 'btn btn-primary btn-addon btn-sm' do %>
            <i class="fa fa-plus"></i>Create Project
          <% end %>
        </div>
      </div>

    </div>

    <div class="col-md-4">
      <div class="row row-sm text-center">

        <!-- Current Projects Stats -->
        <div class="col-xs-6">
          <div class="panel padder-v item">
            <div class="h1 text-info font-thin h1"><%= @user_projects.count %></div>
            <span class="text-muted text-xs">Current Projects</span>
            <div class="top text-right w-full">
              <i class="fa fa-pie-chart text-warning m-r-sm"></i>
            </div>
          </div>
        </div>

        <!-- Contacts in all Projects -->
        <div class="col-xs-6">
          <a href="" class="block panel padder-v bg-primary item">
            <span class="text-white font-thin h1 block"><%= @user_contacts.count %></span>
            <span class="text-muted text-xs">Total Contacts</span>
            <span class="bottom text-right w-full">
              <i class="fa fa-users text-muted m-r-sm"></i>
            </span>
          </a>
        </div>
        <div class="col-xs-6">
          <a href="" class="block panel padder-v bg-info item">
            <span class="text-white font-thin h1 block">432</span>
            <span class="text-muted text-xs">Comments</span>
            <span class="top text-left">
              <i class="fa fa-caret-up text-warning m-l-sm"></i>
            </span>
          </a>
        </div>
        <div class="col-xs-6">
          <div class="panel padder-v item">
            <div class="font-thin h1">129</div>
            <span class="text-muted text-xs">Feeds</span>
            <div class="bottom text-left">
              <i class="fa fa-caret-up text-warning m-l-sm"></i>
            </div>
          </div>
        </div>
        <div class="col-xs-12 m-b-md">
          <div class="r bg-light dker item hbox no-border">
            <div class="col w-xs v-middle hidden-md">
              <div ng-init="data1=[60,40]" ui-jq="sparkline" ui-options="[60,40], {type:'pie', height:40, sliceColors:['#fad733','#fff']}" class="sparkline inline"><canvas width="40" height="40" style="display: inline-block; width: 40px; height: 40px; vertical-align: top;"></canvas></div>
            </div>
            <div class="col dk padder-v r-r">
              <div class="text-primary-dk font-thin h1"><span>$12,670</span></div>
              <span class="text-muted text-xs">Revenue, 60% of the goal</span>
            </div>
          </div>
        </div>


      </div>
    </div>
  </div>

</div>

app/views/projects/new.html.erb
<div class="bg-light lter b-b wrapper-md ng-scope">
  <h1 class="m-n font-thin h3">
    Create a Project
    <span class="badge"><%= current_user.projects.count %></span>
  </h1>
  <small class="text-muted">Bootstrap components written in pure AngularJS</small>
</div>

<div class="container w-xxl w-auto-xs" >

  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>

  <%= form_for(@project) do |f| %>
    <div class="list-group list-group-sm">
      <div class="list-group-item">
        <%= f.text_field :name, class: 'form-control no-border', placeholder: 'Project Name', required: true %>
      </div>
    </div>

    <%= button_tag(type: "submit", class: "btn btn-lg btn-primary btn-block") do %>
      <i class="fa fa-plus"></i> &nbsp;&nbsp; Create Project
    <% end %>
  <% end %>

</div>

app/views/projects/show.html.erb
<div class="bg-light lter b-b wrapper-md ng-scope">
  <h1 class="m-n font-thin h3">
    <%= @project.name %>
  </h1>
</div>

<div class="wrapper-md">
  
  <div class="row">
    
    <div class="col-md-3">

      <!-- Overview Panel -->
      <div class="panel b-a">
        <div class="panel-heading no-border bg-primary">          
          <span class="text-lt">The Restaurant</span>
        </div>
        <div class="item m-l-n-xxs m-r-n-xxs">

          <div class="bottom wrapper bg-gd-dk text-white">            
            <div class="text-u-c h3 m-b-sm text-primary-lter">Coffee</div>
            <div>Restaurant</div>
            <div>9:00 am - 12:00 pm</div>
          </div>
          <img src="http://flatfull.com/themes/angulr/img/c0.jpg" class="img-full">
        </div>
        <div class="hbox text-center b-b b-light text-sm">          
          <a href="" class="col padder-v text-muted b-r b-light">
            <i class="ion-ios-people-outline block m-b-xs fa-2x"></i>
            <span>Contacts</span>
          </a>
          <a href="" class="col padder-v text-muted b-r b-light">
            <i class="ion-ios-chatboxes-outline block m-b-xs fa-2x"></i>
            <span>Inbox</span>
          </a>
          <a href="" class="col padder-v text-muted">
            <i class="ion-ios-settings block m-b-xs fa-2x"></i>
            <span>Settings</span>
          </a>
        </div>
        <div class="hbox text-center text-sm">          
          <a href="" class="col padder-v text-muted b-r b-light">
            <i class="ion-ios-bolt-outline block m-b-xs fa-2x"></i>
            <span>Bugs</span>
          </a>
          <a href="" class="col padder-v text-muted b-r b-light">
            <i class="ion-ios-flask-outline block m-b-xs fa-2x"></i>
            <span>Analytics</span>
          </a>
          <a href="" class="col padder-v text-muted">
            <i class="ion-ios-pulse block m-b-xs fa-2x"></i>
            <span>Delete</span>
          </a>
        </div>
      </div>

      <!-- Import Contact -->

      <button class="btn m-b-xs btn-sm btn-info btn-addon btn-block">
        <i class="fa fa-trash-o"></i> Import Contacts
      </button>


    </div>


    <!-- Right Side -->
    <div class="col-md-9">
      
      <div class="panel panel-default ProjectContactsList">
        <div class="panel-heading">
          Contacts
        </div>
        <div class="table-responsive">

          <table class="table table-striped m-b-none dataTable" id="projectContactList">
            <thead>
              <tr>
                <th class="sorting_asc" colspan="1" rowspan="1" style="width: 198px;" tabindex="0">
                  Name
                </th>

                <th class="sorting" colspan="1" rowspan="1" style="width: 256px;" tabindex="0">
                  Mobile Number
                </th>

                <th class="sorting" colspan="1" rowspan="1" style="width: 255px;" tabindex="0">
                  Responded
                </th>

                <th class="sorting" colspan="1" rowspan="1" style="width: 138px;" tabindex="0">
                  Version
                </th>

                <th class="sorting" colspan="1" rowspan="1" style="width: 138px;" tabindex="0">
                  Something
                </th>
              </tr>
            </thead>

            <tbody>

              <% @project.contacts.each do |contact| %>
                <tr class="<%= cycle("even", "odd") -%>">
                  <td class="sorting_1">
                    <%= link_to contact.name, project_contact_path(@project, contact) %>
                  </td>

                  <td>
                    <%= contact.mobile_phone %>
                  </td>

                  <td>Win 98+ / OSX.2+</td>

                  <td>1.7</td>

                  <td>A</td>
                </tr>
              <% end %>

            </tbody>
          </table>

        </div>
      </div>
      
    </div>

  </div>

</div>