config/routes.rb
Rails.application.routes.draw do

  # Root
  root 'pages#home'

  # Devise
  devise_for :users, path: '',
    path_names: {
      sign_in: 'login',
      sign_out: 'logout',
      sign_up: 'register' }

  # Projects 
  resources :projects do
    collection { post :send_bulk }
    resources :contacts do
      resources :messages
    end
    resources :campaigns
  end

  # Incoming Messages
  post 'incoming_message_webhook' => 'twilio#incoming_message'
 
end

app/models/campaign.rb
class Campaign < ActiveRecord::Base

  # Associations
  belongs_to :user
  belongs_to :project

end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_campaign, only: [:show, :edit, :update, :destroy]

  def index
    @campaigns = Campaign.all
  end

  def show
    @campaign = Campaign.find(params[:id])
  end

  def new
    @campaign = Campaign.new
  end

  def edit
  end

  def create

    @project = Project.find(params[:project_id])
    @campaign = current_user.campaigns.build(campaign_params)
    @campaign.project_id = @project.id

    # Send Individual Messages to Contacts
    @campaign.send_campaign

    if @campaign.save
      redirect_to @project, notice: 'Campaign was successfully send!'
    else
      render :new
    end
  end

  def update
    @campaign.update(campaign_params)
  end

  def destroy
    @campaign.destroy
    redirect_to @project
  end

  private
    def set_campaign
      @campaign = Campaign.find(params[:id])
    end

    def campaign_params
      params.require(:campaign).permit(:name, :body, :references, :references)
    end
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/views/campaigns/_form.html.erb
<%= form_for(@campaign) do |f| %>
  <% if @campaign.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@campaign.errors.count, "error") %> prohibited this campaign from being saved:</h2>

      <ul>
      <% @campaign.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :references %><br>
    <%= f.text_field :references %>
  </div>
  <div class="field">
    <%= f.label :references %><br>
    <%= f.text_field :references %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/campaigns/edit.html.erb
<h1>Editing campaign</h1>

<%= render 'form' %>

<%= link_to 'Show', @campaign %> |
<%= link_to 'Back', campaigns_path %>

app/views/campaigns/index.html.erb
<h1>Listing campaigns</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Body</th>
      <th>References</th>
      <th>References</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @campaigns.each do |campaign| %>
      <tr>
        <td><%= campaign.name %></td>
        <td><%= campaign.body %></td>
        <td><%= campaign.references %></td>
        <td><%= campaign.references %></td>
        <td><%= link_to 'Show', campaign %></td>
        <td><%= link_to 'Edit', edit_campaign_path(campaign) %></td>
        <td><%= link_to 'Destroy', campaign, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Campaign', new_campaign_path %>

app/views/campaigns/new.html.erb
<h1>New campaign</h1>

<%= form_for([@project, @project.campaigns.build]) do |f| %>
  <% if @campaign.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@campaign.errors.count, "error") %> prohibited this campaign from being saved:</h2>

      <ul>
      <% @campaign.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :references %><br>
    <%= f.text_field :references %>
  </div>
  <div class="field">
    <%= f.label :references %><br>
    <%= f.text_field :references %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/campaigns/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @campaign.name %>
</p>

<p>
  <strong>Body:</strong>
  <%= @campaign.body %>
</p>

<p>
  <strong>References:</strong>
  <%= @campaign.references %>
</p>

<p>
  <strong>References:</strong>
  <%= @campaign.references %>
</p>

<%= link_to 'Edit', edit_campaign_path(@campaign) %> |
<%= link_to 'Back', campaigns_path %>